#!/bin/bash

mkdir incs srcs

if [[ "-r" == "$1" ]]; then
	for i in $*
	do
		rm -rf "srcs/$i.cpp"
		rm -rf "incs/$i.hpp"
	done
else
	for i in $*
	do
		touch $i.cpp
		touch $i.hpp
		class_header $i
		class_body	$i
		mv $i.cpp srcs
		mv $i.hpp incs
	done   
fi